# Generated by Django 2.0 on 2020-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200123_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='Attach Resume', upload_to='freelancer_docs'),
        ),
    ]
